services:
  # app:
  #   build: .
  #   container_name: app
  #   ports:
  #     - "8080:8080"
  #   env_file:
  #     - .env
  #   depends_on:
  #     - postgres
  #     - minio

  postgres:
    image: postgres:16.4
    container_name: postgres
    volumes:
      - postgres:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 3s
      retries: 3

  # minio:
  #   image: minio/minio
  #   container_name: minio
  #   volumes:
  #     - minio:/data
  #   ports:
  #     - "9000:9000"
  #     - "9001:9001"
  #   command: server /data --console-address :9001
  #   environment:
  #     - MINIO_ROOT_USER=minio
  #     - MINIO_ROOT_PASSWORD=minio123
  #   healthcheck:
  #     test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/ready"]
  #     interval: 10s
  #     timeout: 3s
  #     retries: 3

  # redis:
  #   image: redis:alpine
  #   container_name: redis
  #   volumes:
  #     - redis:/data
  #   ports:
  #     - "6379:6379"
  #   healthcheck:
  #     test: ["CMD", "redis-cli", "ping"]
  #     interval: 10s
  #     timeout: 3s
  #     retries: 3

volumes:
  postgres:
  minio:
  redis: